from src.rag_execution.classification.classifier import classify_invoice


def main():
    test_invoices = [
        {
            "invoice_id": "INV-001",
            "invoice_amount": "750",
            "po_number": "PO-7001",
            "document_type": "Invoice",
            "po_valid_flag": "Y",
            "vendor_match_flag": "Y",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "Y",
            "expense_permitted_without_po_flag": "N",
            "utility_flag": "N",
            "recurring_flag": "N",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-015",
            "invoice_amount": "3000",
            "po_number": "",
            "document_type": "Invoice",
            "po_valid_flag": "N",
            "vendor_match_flag": "N",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "N",
            "expense_permitted_without_po_flag": "Y",
            "utility_flag": "N",
            "recurring_flag": "N",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-023",
            "invoice_amount": "1975",
            "po_number": "",
            "document_type": "Invoice",
            "po_valid_flag": "N",
            "vendor_match_flag": "N",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "N",
            "expense_permitted_without_po_flag": "N",
            "utility_flag": "Y",
            "recurring_flag": "N",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-031",
            "invoice_amount": "4420",
            "po_number": "",
            "document_type": "Invoice",
            "po_valid_flag": "N",
            "vendor_match_flag": "N",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "N",
            "expense_permitted_without_po_flag": "N",
            "utility_flag": "N",
            "recurring_flag": "Y",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-037",
            "invoice_amount": "-1950",
            "po_number": "",
            "document_type": "Credit Note",
            "po_valid_flag": "N",
            "vendor_match_flag": "N",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "N",
            "expense_permitted_without_po_flag": "N",
            "utility_flag": "N",
            "recurring_flag": "N",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-041",
            "invoice_amount": "2440",
            "po_number": "",
            "document_type": "Invoice",
            "po_valid_flag": "N",
            "vendor_match_flag": "N",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "N",
            "expense_permitted_without_po_flag": "N",
            "utility_flag": "N",
            "recurring_flag": "N",
            "duplicate_flag": "Y",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-047",
            "invoice_amount": "2400",
            "po_number": "PO-9047",
            "document_type": "Invoice",
            "po_valid_flag": "Y",
            "vendor_match_flag": "Y",
            "within_tolerance_flag": "N",
            "goods_receipt_flag": "Y",
            "expense_permitted_without_po_flag": "N",
            "utility_flag": "N",
            "recurring_flag": "N",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-048",
            "invoice_amount": "450",
            "po_number": "",
            "document_type": "Invoice",
            "po_valid_flag": "N",
            "vendor_match_flag": "N",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "N",
            "expense_permitted_without_po_flag": "N",
            "utility_flag": "N",
            "recurring_flag": "N",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "Y",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.95",
        },
        {
            "invoice_id": "INV-049",
            "invoice_amount": "750",
            "po_number": "",
            "document_type": "Invoice",
            "po_valid_flag": "N",
            "vendor_match_flag": "N",
            "within_tolerance_flag": "Y",
            "goods_receipt_flag": "N",
            "expense_permitted_without_po_flag": "Y",
            "utility_flag": "N",
            "recurring_flag": "N",
            "duplicate_flag": "N",
            "mandatory_fields_missing_flag": "N",
            "supplier_valid_flag": "Y",
            "confidence_score": "0.88",
        },
    ]

    for invoice in test_invoices:
        result = classify_invoice(invoice)
        print("\n-----------------------------")
        print(f"Invoice ID: {result['invoice_id']}")
        print(f"Classification: {result['predicted_classification']}")
        print(f"Route: {result['predicted_route']}")
        print(f"Review Required: {result['review_required']}")
        print(f"Reason: {result['reason']}")


if __name__ == "__main__":
    main()